# Generated by Django 4.2.7 on 2023-11-08 14:50

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('start_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('cash_due', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cash_received', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cash_taken', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('keterangan', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('admin', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('pointer', models.CharField(max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('time', models.TimeField(default=django.utils.timezone.localtime)),
                ('old', models.CharField(max_length=255, null=True)),
                ('new', models.CharField(max_length=255, null=True)),
                ('admin', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
