# Generated by Django 5.0 on 2024-01-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='keterangan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
