# Generated by Django 4.2.7 on 2023-11-08 14:50

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Purchasing', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='masuk_gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('waktu', models.TimeField(default=django.utils.timezone.localtime)),
                ('admin', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pengiriman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_masuk', to='Purchasing.pengiriman')),
            ],
        ),
        migrations.CreateModel(
            name='keluar_gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('waktu', models.TimeField(default=django.utils.timezone.localtime)),
                ('admin', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('transaksi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_keluar', to='Sales.transaksi')),
            ],
        ),
        migrations.CreateModel(
            name='item_masuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('jumlah_awal', models.PositiveIntegerField(default=0)),
                ('gudang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.gudang')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Purchasing.item_pengiriman')),
                ('item_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_masuk', to='Inventory.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_dalam_record_masuk', to='Inventory.masuk_gudang')),
            ],
        ),
        migrations.CreateModel(
            name='item_keluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('jumlah_awal', models.PositiveIntegerField(default=0)),
                ('gudang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.gudang')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.item_transaksi')),
                ('item_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_keluar', to='Inventory.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_dalam_record_keluar', to='Inventory.keluar_gudang')),
                ('stack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.stack')),
            ],
        ),
    ]
