# Generated by Django 4.2.7 on 2023-11-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0006_rename_item_item_pengiriman_item_po'),
        ('Inventory', '0002_masuk_gudang_keluar_gudang_item_masuk_item_keluar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_masuk',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_diterima', to='Purchasing.item_pengiriman'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='jumlah',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
