# Generated by Django 5.0 on 2023-12-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_item_masuk_item_alter_stack_jumlah'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_keluar',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item_masuk',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
