# Generated by Django 5.0 on 2023-12-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_item_keluar_keterangan_item_masuk_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_keluar',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='item_masuk',
            name='keterangan',
        ),
    ]
