# Generated by Django 5.0 on 2024-01-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_remove_item_keluar_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gudang',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
