# Generated by Django 4.2.7 on 2023-11-08 14:50

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_invoice', models.CharField(max_length=16)),
                ('penjual', models.CharField(max_length=16)),
                ('ekspedisi', models.CharField(max_length=16)),
                ('tanggal', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('status_pembayaran', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('keterangan', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.PositiveIntegerField()),
                ('jumlah', models.PositiveIntegerField()),
                ('keterangan', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_invoice', to='Purchasing.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_dalam_invoice', to='Inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tanggal_sampai', models.DateField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('admin', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengiriman_dalam_invoice', to='Purchasing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='item_pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongkos', models.PositiveIntegerField()),
                ('jumlah', models.PositiveIntegerField()),
                ('jumlah_terima', models.PositiveIntegerField(default=0)),
                ('keterangan', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_dalam_pengiriman', to='Purchasing.item_invoice')),
                ('pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pengiriman', to='Purchasing.pengiriman')),
            ],
        ),
    ]
