# Generated by Django 4.2.7 on 2023-11-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice',
            new_name='purchase_order',
        ),
    ]
