# Generated by Django 4.2.7 on 2023-11-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_masuk_gudang_keluar_gudang_item_masuk_item_keluar'),
        ('Purchasing', '0003_alter_item_invoice_invoice_alter_item_invoice_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item_invoice',
            new_name='item_PO',
        ),
    ]
