# Generated by Django 4.2.7 on 2023-11-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0004_rename_item_invoice_item_po'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_po',
            old_name='invoice',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='pengiriman',
            old_name='invoice',
            new_name='purchase_order',
        ),
    ]
