# Generated by Django 5.0 on 2023-12-21 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0007_remove_item_pengiriman_jumlah_terima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pengiriman',
            name='item_PO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_dalam_pengiriman', to='Purchasing.item_po'),
        ),
    ]
