# Generated by Django 5.0 on 2023-12-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0008_alter_item_pengiriman_item_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='ekspedisi',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
