# Generated by Django 4.2.7 on 2023-11-08 14:50

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelanggan', models.CharField(max_length=16)),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('waktu', models.TimeField(default=django.utils.timezone.localtime)),
                ('pembayaran', models.CharField(max_length=10)),
                ('status_pembayaran', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('keterangan', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('admin', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_transaksi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='print_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_key', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
                ('nominal_pembayaran', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('time', models.TimeField(default=django.utils.timezone.localtime)),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.transaksi')),
            ],
        ),
        migrations.CreateModel(
            name='item_transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga', models.PositiveIntegerField()),
                ('keterangan', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='barang_terjual', to='Inventory.item')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_dalam_transaksi', to='Sales.transaksi')),
            ],
        ),
    ]
