# Generated by Django 5.0 on 2023-12-21 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_transaksi_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_request',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.transaksi'),
        ),
    ]
