# Generated by Django 5.0 on 2023-12-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_print_request_transaksi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print_request',
            old_name='nominal_pembayaran',
            new_name='nominal_bayar',
        ),
    ]
