# Generated by Django 5.0 on 2024-01-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_rename_nominal_pembayaran_print_request_nominal_bayar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='tanggal_pembayaran',
            field=models.DateField(default=None, null=True),
        ),
    ]
